### ISSUE TITLE
Startup screen "Recent" and "Open Project" glitch when scrolling

### ISSUE THREAD

**Issue by taaavi** [atg/chocolat-public#1000]
Did quick search, but didn't find ticket on this.

When scrolling, background will start covering the buttons on the top right corner ("Recent" and "Open Project" buttons).
 
Glitch can be seen here:
http://cl.ly/1f2u1C2D423D2L2Q1r2i

Mostly happens when scrolling vigorously. 
Perhaps not the most critical bug, but somewhat annoying nonetheless.

Lion 10.7.4

**Comment by locks** [comment]
This should be fixed.
