### ISSUE TITLE
creating a new file doesn't open it, and doesn't show up in project bar

### ISSUE THREAD

**Issue by mjbaldwin** [atg/chocolat-public#1023]
Chocolat 1.0 on OSX 10.7.4.

About half the time, when I right-click on the project bar and select "New file...", and create a new file, the file gets created...

BUT, it doesn't show up in the project bar, and it doesn't open.

I have to go to "File > Open..." to find it using the dialog to open. Only then does the project bar get updated to show it.

Unfortunately I can't tell what's different when this works and doesn't -- it breaks about half the time. I usually have the same project open in multiple tabs at the top (with different sets of files open in each), but the bug doesn't seem to depend on which tab is open, for example.

**Comment by locks** [comment]
This should be fixed for a while now.
