### ISSUE TITLE
copy-paste: indentation of first line is wrong

### ISSUE THREAD

**Issue by mjbaldwin** [atg/chocolat-public#1157]
So I've been using Chocolat for a couple of months now, and absolutely love it. But this bug (or feature? not sure) is the one thing that drives me absolutely nuts. This is, no question, my #1 request to fix.

It's the fact that, very often, when I copy lines of code, and paste them elsewhere, the first line of text gets pasted with a different indentation level from the rest of the following lines.

This drives me nuts, because every time I first paste, then fix the indentation of the first line to match the rest of the code, and *then* re-select the whole block, and then adjust the indentation of the whole block to be where I want it to be.

Here are three examples of how it breaks. Just create a plain text file for any of these (I use soft tabs, 2 spaces).

---

EXAMPLE 1

Type:

```
ABC
  DEF
    GHI
```

Copy it, paste it on a new line, and you get:

```
ABC
DEF
  GHI
```

--- 

EXAMPLE 2

Type:

```
  ABC
DEF
  GHI
```

Copy-and-paste, and you get:

```
  ABC
  DEF
    GHI
```

---

Example 3:

Type:

```
  ABC
  DEF
GHI
```

Copy-and-paste, and you get:

```
  ABC
    DEF
  GHI
```

---

So that's it. I'm assuming Chocolat is trying to do something "smart", but it's just not getting it right, and this is really a huge thing, since I'll use copy-paste to move or duplicate little chunks *all the time*. And like happens in every other editor, I just want to move my cursor to the beginning of a new line, hit Cmd+V, have the newly selected code be highlighted, and then use Cmd+[, ] to adjust its indent to the correct level.

Maybe if Chocolat's smart-indentation worked, without messing up the internal indentation of my code, I'd like that better. But right now I can't tell.

Thanks!

**Comment by pucuz** [comment]
Add me to this also. Please fix this.

**Comment by tayler1** [comment]
@atg @locks please fix this

**Comment by randybruder** [comment]
> Just found the ctrl>cmd>v. That seems to do what I want. That should be default

That's a pretty easy fix to do youself:
![image](https://cloud.githubusercontent.com/assets/6447487/16071697/d1cafb84-32aa-11e6-9c51-6668575ac91a.png)

**Comment by atg** [comment]
Pasting works a lot better for me in 3.3 beta, but @locks doesn't like it. I'm going to close this anyway.
