### ISSUE TITLE
Java compile and run fails with error

### ISSUE THREAD

**Issue by khagler** [atg/chocolat-public#1439]
1. Enter a Java "hello world" and save it as Example.java.
2. Choose the Actions->Java->Compile & Run menu item.
3. The Command Output window appears with the following error:

/Applications/Chocolat.app/Contents/SharedSupport/Truffles/java.truffle/support/bin/javamate.rb:3:in `require': no such file to load -- /Applications/Chocolat.app/Contents/SharedSupport/Support/lib/tm/executor (LoadError) from /Applications/Chocolat.app/Contents/SharedSupport/Truffles/java.truffle/support/bin/javamate.rb:3

**Comment by lperry65** [comment]
Just tried to build and run a Java file within a package, build creates a Build folder with the package folder hierarchy as sub folders and the compiled class file. It then fails to run with ( Error: Could not find or load main class xxxx )
