### ISSUE TITLE
Tabs size indentation is not the same as its equivalent in spaces.

### ISSUE THREAD

**Issue by ignism** [atg/chocolat-public#1558]
A tab and spaces (same amount as a tab) are not the same length. If I use tabs, or if I convert my spaces to tabs I am not able to align text as you would expect it would do using a monospace font.
However if I convert all my tabs to spaces, it does cleanly align my code. notice the shift on lines 14 and 15 in the following pictures.
![shift0](https://f.cloud.github.com/assets/2485645/2428093/56d45324-ac2b-11e3-8f30-90ed930ad8bc.png)
![shift1](https://f.cloud.github.com/assets/2485645/2428094/56d45694-ac2b-11e3-9884-8ed5f7a8d9bb.png)

**Comment by atg** [comment]
I guess this isn't an issue any more? it looks fixed on my end, but I don't remember ever fixing it. spooky 👻
