### ISSUE TITLE
Let us choose the Markdown file extension 

### ISSUE THREAD

**Issue by simontaen** [atg/chocolat-public#1559]
Dear All

I'm always a bit annoyed when I see Chocolat trying to save Markdown files as "mdown" files. Especially since my QuickLook plugin isn't able to read "mdown". Personally I have not seen another app using it. I would prefer the much more common "md", but people have different taste. Letting them choose mit be the best option.

Cheers
Simon

**Comment by simontaen** [comment]
Any update on this? Still annoyingl. Lots of tool don't recognize `.mdown` as markdown and I have to find workarounds and create special cases.

**Comment by atg** [comment]
ok fixed in whatever version number we decided was next. Now defaults to ".md"

**Comment by simontaen** [comment]
awesome thanks!
