### ISSUE TITLE
Margin guideline broken in Yosemite

### ISSUE THREAD

**Issue by bryanenders** [atg/chocolat-public#1654]
While the guideline and the shading work fine in Mavericks, in Yosemite they only show up _below_ the text (instead of alongside).

![screen shot 2014-10-21 at 10 46 08 am](https://cloud.githubusercontent.com/assets/2033828/4720539/c0f90912-5931-11e4-90b9-fe5e05e7f62d.png)

**Comment by endersstocker** [comment]
Is the fix part of the next release? Is there a target date for the next release?

**Comment by fileability** [comment]
The fix is out now
