### ISSUE TITLE
Inconsistent fonts in sidebar

### ISSUE THREAD

**Issue by mattbeshara** [atg/chocolat-public#1743]
On OS X 10.11, files and folders use Lucida Grande, while headers use San Francisco. Files and folders should probably use the system font.
<img width="98" alt="screen shot 2015-11-13 at 9 43 57 am" src="https://cloud.githubusercontent.com/assets/13046881/11133647/1ae3532a-89eb-11e5-839f-488866c93aef.png">

**Comment by fileability** [comment]
Yes I patched it to use lucida grande when apple switched it to helvetica since it was too hard to read at that size. I will see how san francisco fares.
