### ISSUE TITLE
the new split view in 3.2.2 will not drag up/down easily  

### ISSUE THREAD

**Issue by rlb222** [atg/chocolat-public#1768]
This is a problem I have with the Chocolat 3.2.2 version. I am on OS 10.9.5. 

Getting to scroll the filesview up and down has become very difficult in this version. 

You 'Wrote a new split view.' thanks, but I have a problem with the detection/appearing of the vertical drag icon. Which is the normal pointer. It only appears on a few pixel wide area. Left of the drag bar itself. On the drag bar and far to the right of the dragbar, the horizontal drag icon (a line and two arrows) appears. 

So the horizontal drag icon will appear easily, but the vertical is difficult. Thus scrolling the filesview up and down has become very difficult.

I reinstalled  3.2.1 and the difference was huge. This version lets me vertical scroll with ease. 
I am back at 3.2.1 for the time being.

**Comment by atg** [comment]
Oh I see what you're saying. If you have a mouse connected, then it's hard to drag the scrollbar. Yeah I guess we just need to bias it over to the right a bit more if scrollbars are visible.

**Comment by atg** [comment]
OK fix will be out in 3.2.3. Thanks!

**Comment by rlb222** [comment]
Thankyou!!
René
