### ISSUE TITLE
Move to trash functionality not working properly

### ISSUE THREAD

**Issue by ujvaljoshi** [atg/chocolat-public#1772]
OS Version: 10.11.3
Chocolat Version: 3.2.4

I have selected multiple files. But when i click "move to trash" option it delete only one file. Ideal behaviour should be delete all selected files.

![screenshot 2016-02-18 11 30 27](https://cloud.githubusercontent.com/assets/870044/13135065/29cbab78-d633-11e5-86bd-0fbd491b1391.png)

**Comment by atg** [comment]
I can see where you're coming from, but if we did it that way, how would you delete _one_ file with multiple files open in splits?

**Comment by ujvaljoshi** [comment]
Yes i get it. I think split view is more useful than multiple move to trash functionality.
