### ISSUE TITLE
Chocolat v3.3 update from v3.2.4 on OS X 10.9.5 overwrites v3.2.4 but is incompatible on 10.9.5!

### ISSUE THREAD

**Issue by DerekCurrie** [atg/chocolat-public#1789]
I'm on a 15" MacBook Pro running **OS X 10.9.5**. I ran Chocolat 3.2.4 today and noticed there was an update to v3.3. I ran the v3.3 updater from within Chocolat. What resulted was v3.3 in my Applications folder, except that version is _NOT_ compatible with 10.9.5 and cannot run. Oops! I'm disabled! That should not have happened. Updaters these days are smart enough to not install updates that are incompatible with the running OS X version. Talk to Apple about avoiding this catastrophe please! This should _never, ever_ happen. It's the _only_ time I've ever seen this occur. All over similarly incompatible updates are blocked.

Meanwhile, I was smart enough to hang onto the v3.2.4 separate installer and will be restoring functionality on my own.

Please don't let this happen again. Thank you.

**Comment by atg** [comment]
chocolatapp.com/release-blog

**Comment by DerekCurrie** [comment]
On Jun 17, 2016, at 6:25 AM, Alex Gordon <notifications@github.com> wrote:

> chocolatapp.com/release-blog
> 

… And? The blog has nothing to do with the PROBLEM I pointed out, does it.

So are you going to REPAIR the problem? Or is this pass-the-buck, or ignore-the-buck time? You’ve got a customer damaging problem to fix.





~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
Derek Currie
derekcurrie@mac.com
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

**Comment by atg** [comment]
The issue is fixed
