### ISSUE TITLE
javascript coloration issue

### ISSUE THREAD

**Issue by AlexandreBernard** [atg/chocolat-public#1790]
not sure this has been posted yet.

coloration issue with version 3.3. see attached screenshot

problem:

![capture d ecran 2016-06-21 a 17 27 37](https://cloud.githubusercontent.com/assets/37109/16235573/b0fe39c2-37d5-11e6-9f09-f0dd4474b084.png)

adding a space makes coloration work:

![capture d ecran 2016-06-21 a 17 27 48](https://cloud.githubusercontent.com/assets/37109/16235577/b3137a60-37d5-11e6-9447-4d246eb85e5f.png)

**Comment by atg** [comment]
Yeah I know about this. Need a lookbehind on the JSX tag regex.

**Comment by atg** [comment]
Something along the lines of `(?<=return|yield|[(\[{=,;:])\s*<[a-z]+etc`

**Comment by atg** [comment]
OK fixed

**Comment by AlexandreBernard** [comment]
amazing :)

**Comment by atg** [comment]
OK 3.3.1 is out now.
