### ISSUE TITLE
Makefile Support

### ISSUE THREAD

**Issue by samdmarshall** [atg/chocolat-public#1794]
I would like some official support for syntax highlighting of Makefiles. I've attempted to import the bundle from TextMate but that has only given be highlighting for comments, even though it defines all the other types of directives that could be used in Makefiles. Additionally the symbol highlighter/current symbol feature seems to be completely broken within Makefiles, so that feature is rather useless to me while editing.

Thanks,
Samantha

**Comment by tonyduan** [comment]
@samdmarshall Why is this issue closed? I would also love to see Makefile support!

**Comment by samdmarshall** [comment]
I closed the issue because I gave up hoping for support on this and have abandoned using Chocolate as an editor entirely so I was doing some issue cleanup.

**Comment by tonyduan** [comment]
Ok -- I'll make a new issue for this; hope that's ok.
