### ISSUE TITLE
Syntax Highlighting stops in mid-file

### ISSUE THREAD

**Issue by bobrocke** [atg/chocolat-public#1810]
This is part of a .scss file and syntax highlighting starts off fine and then just stop in mid-file. See line 411 to 412.

![highlight](https://cloud.githubusercontent.com/assets/2962426/24841563/4cf82030-1d55-11e7-91ba-b9ec345fac7e.jpeg)

**Comment by bobrocke** [comment]
Is this repeatable? Do others see it, too?

Maybe it has something to do with file size?

**Comment by owebboy** [comment]
Are you sure you are using the right syntax highlighter? There is sass and scss. Check this issue: #1596

**Comment by bobrocke** [comment]
!!!

That was it.

Installing with the instructions here: https://github.com/MarioRicalde/SCSS.tmbundle/tree/Chocolat didn't work quite right. But I renamed the folder I unzipped to `SCSS.truffle` and manually installed it at: `~/Library/Application Support/Chocolat/Truffles/SCSS.truffle` and then things worked.

Thanks for the clue!
