### ISSUE TITLE
'choc' command line tool does not work in macOS High Sierra

### ISSUE THREAD

**Issue by mikegabriel** [atg/chocolat-public#1821]
Using Chocolat 3.4, running 'choc <filename or directory>' simply launches Chocolat and does not open the specified file or folder.

Seems to be related to High Sierra since it was working pre-update.

**Comment by gobijan** [comment]
Cannot confirm this. Works for me. Make sure you invoke it like this for the current path you're in:
`choc .`
So make sure you pass the path.

**Comment by mikegabriel** [comment]
Yeah, it's working now.  Probably was some glitch that persisted a couple reboots but I haven't seen it crop up for a week or so now.
