### ISSUE TITLE
Context menu for files in project bar

### ISSUE THREAD

**Issue by mmopy** [atg/chocolat-public#869]
It would be nice to have a right-click (contact) menu for the files in the project bar. It would have the following functionality if you click a file:

Rename
Delete
Show in Finder
Get info (open Finder Get Info page)
Copy path
Duplicate (duplicates xxx and calls it xxx copy)
Open in split view (just a possible one)

If you click a folder:

Rename
Delete
Show in Finder
Get info (open Finder Get Info page)
Copy path
Duplicate (duplicates xxx and calls it xxx copy)

If you click blank space:

New file
New folder

I know that Chocolat is an editor first - but these few project management options would greatly speed working with a project that has multiple files.

Thanks for the great product

**Comment by uweschmelzer** [comment]
+1 for Copy path in context menu
(Should I open a new issue for that?)

**Comment by atg** [comment]
That's a good idea. Might have to sherlock that mixin.

**Comment by uweschmelzer** [comment]
Yeah!
:)
